export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH';
export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const SET_FILTERED_VIDEOS = 'SET_FILTERED_VIDEOS';
export const SET_FILTERED_VIDEOS_NAMES = 'SET_FILTERED_VIDEOS_NAMES';
export const TOGGLE_SEARCH_BOX = 'SET_CLICKED_SEARCH_BOX';
